### ISSUE TITLE
第5章的strcmp实现有点小问题&修改建议

### ISSUE THREAD

**Issue by UKeeySDis** [hurley25/hurlex-doc#10]
源代码`libs/string.c`中实现`strcmp`函数时的源代码是：

    inline int strcmp(const char *str1, const char *str2)
    {
	    while (*str1 && *str2 && (*str1++ == *str2++))
	    ;
        if (*str1 == '\0' && *str2 == '\0') {
	           return 0;
	    }

	    if (*str1 == '\0') {
	      return -1;
	    }
	    return 1;
    }
这样如果两个字符串长度相等但字符串不同时，检测出来的结果就不对，大神应该当时没有注意到，算是一个小瑕疵吧。修正代码：
       
    inline int strcmp(const char *str1, const char *str2)
    {
	    while(*str1 == *str2)
	    {
		    if(*str1 == '\0')
			    return 0;
		    str1++;
		    str2++;
	    }
	    return *str1 - *str2;
    }
同时感谢大神的文档，比看《Orange's 一个操作系统的实现》要简易很多。

**Comment by hurley25** [comment]
有没有测试的case呢？具体传入什么字符串会导致返回0呢？

**Comment by UKeeySDis** [comment]
如果两个字符串的长度和字符都相等才会返回0。比如字符串`str1="test a"`和字符串`str2="test b"`,按照之前的源码当判断到两个字符串最后的字符`a`和`b`时，由于不相等会出`while`循环，但是代码中进行了`++`操作，就直接到达两个字符串的结束符位置了，然后会进`if(*str1 == '\0' && *str2 == '\0'`这个条件，返回0，但是其实这两个字符串虽然长度相同但并不相等。
测试代码(调用了库中的`strcmp`做比较)：
    
    #include <stdio.h>
    #include <string.h>

    int my_strcmp(const char *str1, const char *str2)
    {
	    while (*str1 && *str2 && (*str1++ == *str2++))
		    ;
	    if (*str1 == '\0' && *str2 == '\0') {
		    return 0;
	    }

	    if (*str1 == '\0') {
		    return -1;
	    }
	    return 1;
    }

    int main()
    {
	    char *str1 = "test a";
	    char *str2 = "test b";

	    printf("%d\n", my_strcmp(str1, str2));
	    printf("%d\n", strcmp(str1, str2));

	    return 0;
	
    }

**Comment by hurley25** [comment]
嗯， 是的，这个函数是有问题的。记不清这个字符串库是从哪里来的了。直接改成这样就行：
```c
int my_strcmp(const char *str1, const char *str2)
{
    while (*str1 && *str2 && *str1 == *str2) {
        str1++;
        str2++;
    }

    return *str1 - *str2;
}
```
