### ISSUE TITLE
從實模式進入保護模式

### ISSUE THREAD

**Issue by amikai** [hurley25/hurlex-doc#13]
以下這段程式碼, 沒有設置 cr0 算是進入保護模式了嘛
```
gdt_flush:
    mov eax, [esp+4]  ; 参数存入 eax 寄存器
    lgdt [eax]        ; 加载到 GDTR [修改原先GRUB设置]

    mov ax, 0x10      ; 加载我们的数据段描述符
    mov ds, ax        ; 更新所有可以更新的段寄存器
    mov es, ax
    mov fs, ax
    mov gs, ax
    mov ss, ax
    jmp 0x08:.flush   ; 远跳转， 0x08 是我们的代码段描述符
              ; 远跳目的是清空流水线并串行化处理器
.flush:
    ret
```

**Comment by hurley25** [comment]
进入保护模式了工作grub做过了，文档有描述：

最后我再列出当GRUB载入我们的内核时，CPU的一些状态信息:

CS 指向基地址为 0x00000000，限长为4G – 1的代码段描述符。
DS，SS，ES，FS 和 GS 指向基地址为0x00000000，限长为4G–1的数据段描述符。
A20 地址线已经打开。
页机制被禁止。
中断被禁止。
EAX = 0x2BADB002
系统信息和启动信息块的线性地址保存在 EBX中(相当于一个指针)。
