### ISSUE TITLE
第五章 文章描述的一点疑惑

### ISSUE THREAD

**Issue by nekopara-orz** [hurley25/hurlex-doc#24]
在你的文章第五章第516行有此描述
### _举个例子，一个函数想使用ebx寄存器那么必须在返回前恢复ebp原先的值，而使用edx寄存器就无需暂存和恢复_

我想咨询的就是，为什么想使用ebx寄存器那么必须在返回前恢复ebp原先的值，而不是恢复ebx寄存器自身的值。

**Comment by hurley25** [comment]
恢复ebx寄存器自身的值是什么意思？
ebx寄存器在调用这个函数前的原值是1，如果函数中使用了ebx寄存器，最后函数ret前，必须把ebx设置为原值1

**Comment by nekopara-orz** [comment]
好的谢谢
这个困扰了我好一会，我以为这两个寄存器有什么联系
