### ISSUE TITLE
“八，完成中断请求和定时器中断”捕获不到键盘的中断？

### ISSUE THREAD

**Issue by xing393939** [hurley25/hurlex-doc#28]
博主好，我参考你的第八节内容编写捕获irq中断，文章地址：http://wiki.0xffffff.org/posts/hurlex-8.html
其中提到IRQ1是 键盘中断，中断向量是33，但是我在irq_handler函数中写了打印代码来验证。
程序正常运行后，我键盘打字，第一次捕获到了，但是之后就一直捕获不到，这个是因为什么呢？
（我的模拟器qemu是qemu-system-i386）

**Comment by xing393939** [comment]
已解决，要先读一下键盘

**Comment by Reven2** [comment]
> 已解决，要先读一下键盘

我也碰到了这个问题 请问具体如何解决呢 就是怎么读一下键盘？

**Comment by xing393939** [comment]
现在有点忘记了，应该是当中断事件发生时，要调用`inb(KBD_BUF_PORT);`复位一下，不然键盘无法继续写入。或者你可以参考一下我的代码仓库https://github.com/xing393939/ostep-study/tree/master/hurlex-doc/chapt8：

**Comment by Reven2** [comment]
> 现在有点忘记了，应该是当中断事件发生时，要调用`inb(KBD_BUF_PORT);`复位一下，不然键盘无法继续写入。或者你可以参考一下我的代码仓库[https://github.com/xing393939/ostep-study/tree/master/hurlex-doc/chapt8：](https://github.com/xing393939/ostep-study/tree/master/hurlex-doc/chapt8%EF%BC%9A)

已经解决 多谢您的帮助
