### ISSUE TITLE
使用grub可能不是个好主意

### ISSUE THREAD

**Issue by xylcbd** [hurley25/hurlex-doc#3]
想要自己制作操作系统的人应该都是极具好奇心的，想知道所有的一切，而使用grub会导致一种错觉，“这个操作系统底下还有秘密”。

**Comment by amikai** [comment]
想請問這篇教學裡沒提到 A20 Line 這個問題的原因是因為 grub 已經處理了?

**Comment by hurley25** [comment]
是的，grub 处理过了，如果对这些历史有兴趣的话可以参阅  https://wiki.osdev.org/A20_Line
