### ISSUE TITLE
对heap.c中split_chunk()的疑问。

### ISSUE THREAD

**Issue by LastAvenger** [hurley25/hurlex-doc#5]
Hi, hurley:

在heap.c中，分割内存块的函数`split_chunk(header_t *chunk, uint32_t len)`，其中`len`是期望获得的chunk的长度，那么分割出来的newchunk的长度不应该是 
`newchunk = chunk + len`吗？

> mm/heap.c  line 137 function split_chunk()
```C
if (chunk->length - len > sizeof (header_t)) {
-		header_t *newchunk = (header_t *)((uint32_t)chunk + chunk->length);
+		header_t *newchunk = (header_t *)((uint32_t)chunk + len);
                ... ... 
}
```

不知道我的想法有没有错，望解答 :）

**Comment by hurley25** [comment]
嗯，看起来是有点问题，你可以提个pull request的。这里的代码来自James的文档，我还真没有写测试。很抱歉对你造成了困扰，现在的hurlex-II使用链表的封装实现这块代码，相对来说可读性好一些：
https://github.com/hurley25/Hurlex-II/blob/master/mm/slob.c

**Comment by LastAvenger** [comment]
好的，谢谢你的答复以及文档，受益良多。
待会我提个PR。
