### ISSUE TITLE
修改并改再次编译启动后，floppy的内容没有变化

### ISSUE THREAD

**Issue by l1nxy** [hurley25/hurlex-doc#7]
我知道我这个问题可能很小白。但是真心不知道去问谁好…
就是修改完代码完，虚拟机输出 的并没有变化

**Comment by hurley25** [comment]
嗯，应该是编译好的内核没有复制进去，仔细看看编译后的输出信息。应该是有挂载软盘，复制文件和卸载软盘的操作~

**Comment by hurley25** [comment]
.PHONY:update_image
update_image:
	sudo mount floppy.img /mnt/kernel
	sudo cp hx_kernel /mnt/kernel/hx_kernel
	sleep 1
	sudo umount /mnt/kernel

makefile里的这几行就是做这个事情的，挂载floppy.img到 /mnt/kernel目录（你没有这个目录就自己建立个），然后复制编译好的 hx_kernel 文件过去，如果你改了文件名字，那就修改这里。

**Comment by l1nxy** [comment]
make qemu的话  是不更新的
我现在是分开做的先make
再手动启动qemu

**Comment by l1nxy** [comment]
在线文档错误有点多…很多图片都挂了…

**Comment by hurley25** [comment]
[墙]

**Comment by goalong** [comment]
多谢啊，解决了我的疑问。
