### ISSUE TITLE
可能是手误

### ISSUE THREAD

**Issue by Veklip** [hurley25/hurlex-doc#8]
hurley，你好啊
【第八章】
时钟中断对于操作系统内核来说很重要的一种中断，它使得CPU无论在执行任何用户或者内核的程序时，都能定义的将执行权利

难道是“都能定时的将执行权利”。如果不是手误请改成容易理解一点的方式。

**Comment by hurley25** [comment]
是的，有误，有问题可以修改了提merge request，我会合并的。

**Comment by hurley25** [comment]
已修改latex文件。
