### ISSUE TITLE
第12章代码有小误&解决方案

### ISSUE THREAD

**Issue by Acculivia** [hurley25/hurlex-doc#9]
在我的ubuntu上面用make编辑，结果为（略去成功的……部分）：
>    编译代码文件 init/entry.c ...
gcc -c -Wall -m32 -ggdb -gstabs+ -nostdinc -fno-builtin -fno-stack-protector -I include init/entry.c -o init/entry.o
In file included from init/entry.c:30:0:
include/common.h:37:13: warning: inline function ‘disable_intr’ declared but never defined
 inline void disable_intr();
             ^
include/common.h:34:13: warning: inline function ‘enable_intr’ declared but never defined
 inline void enable_intr();
             ^
链接内核文件...
ld -T scripts/kernel.ld -m elf_i386 -nostdlib  ./idt/idt_s.o  ./gdt/gdt_s.o  ./kernel/sched/switch_to.o  ./boot/boot.o  ./libs/common.o  ./libs/string.o  ./idt/idt.o  ./mm/heap.o  ./mm/pmm.o  ./mm/vmm.o  ./mm/page_fault.o  ./gdt/gdt.o  ./drivers/timer.o  ./drivers/console.o  ./kernel/task/task.o  ./kernel/sched/sched.o  ./kernel/debug/elf.o  ./kernel/debug/printk.o  ./kernel/debug/debug.o  ./init/entry.o -o hx_kernel
./init/entry.o: In function `kern_init':
********/hurlex-doc-master/code/chapt12/init/entry.c:133: undefined reference to `enable_intr'
Makefile:37: recipe for target 'link' failed
make: *** [link] Error 1

在[这里](http://stackoverflow.com/questions/1421666/qt-creator-inline-function-used-but-never-defined-why)我了解到inline函数最好在头文件中被定义。我看了看`common.h`，发现恰好只有dis和en函数的声明被写了inline。
最终我的解决方法是把这两个inline给删掉了。我也尝试过直接把`common.c`的那两段函数剪过来，但是还是发现没有用。其实我对c语言的编译链接绝对不了解所以我打算就这样？_(:з」∠)_放issue而不是pull的原因是因为我也有点想知道对于这种问题怎样子做更好。。。。。

大大写出来的东西对我在操作系统方面的学习上有着很大的帮助，支持大大！

**Comment by hurley25** [comment]
是的，你说的没错，这里是有问题的。
可以这样做，将common.c的函数移到common.h里去，然后再加 static就可以，即static inline，因为不加static的话，等价于所有包含了这个.h的文件都会有这个函数的定义，链接时可能会报重定义（有些未完全内联的情况），static之后作用域限制在文件内，符号（这里指函数名）对链接器不可见就没问题了。

**Comment by hurley25** [comment]
移动到头文件里了，已修正，感谢指出问题。
